- name: files from variables
  hosts: local
  connections: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course inforamtion
    ansible.builtin.debug:
      msg: "hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"