- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter your username
    private: true

  - name: password
    promp: please enter your password
    private: true
  tasks:
  - name: printing user information 
    ansible.builtin.debug:
      msg: "hello username is: {{ USERNAME }}, password is: {{ PASSWORD }}"