- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course inforamtion  
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"