- name: fuctions
  hosts: local
  connection: local
  vars:
    Persons: "priya, navi, gowtam, prami"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ Person | default('priya') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ Person | split(',')  }}"
  - name: covert map into list
    vars:
      course:
      name: ansible
      duration: 10HR
      trainer: priyanka
    ansible.builtin.debug: 
      msg: "Course Info: {{ course | dict2items }}"

  - name: covert map into list
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'priyanka'}
    ansible.builtin.debug: 
      msg: "Course Info: {{ course | items2dict }}"