- name: fuctions
  hosts: local
  connection: local
  vars:
    Person: "priya, navi, gowtam, prami"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ Person | default('priya') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ Person | split(',')  }}"
  - name: covert map into list
    vars:
      course:
      name: ansible
      duration: 10HR
      trainer: priyanka
    ansible.builtin.debug: 
      msg: "Course Info: {{  course | dct2items }}""

  - name: covert map into list
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'priyanka'}
    ansible.builtin.debug: 
      msg: "Course Info: {{ course | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "priyanka reddy"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "priyanka reddy"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check the ip address is valid or not 
    vars: 
      ip: "300.567.980.789"
    ansible.builtin.debug:
      msg: " {{ ip | ansible.utils.ipaddr }}"