- name: fuctions
  hosts: local
  connection: local
  vars:
    persons: "priya,navi,gowtam,prami"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ Person | default('priya') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ Person  }}"

 